name: React Tests with Jest
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      # Install required deps for action
      - name: Install Dependencies
        working-directory: ./src/react
        run: yarn install

      # Run ESlinter
      - name: Run ESlinter
        working-directory: ./src/react
        run: yarn run eslint src

      # Finally, run our tests
      - name: Run the tests
        working-directory: ./src/react
        run: yarn test