# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
build:
  runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Use Node.js 18.9.0
uses: actions/setup-node@v1
with:

  - run: npm ci
//before the first 'run' each "run" is a script from your project:
  - run: npm run prettier
  - run: npm run linter
  - run: npm test