# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
push:
branches: [ master ]
pull_request:
branches: [ master ]
jobs:
build:
runs-on: ubuntu-latest
strategy:
max-parallel: 24
matrix:
//Set which OS you want to run the builds and tests:
os: [ubuntu-latest, macos-latest, windows-latest]
steps:
- uses: actions/checkout@v2
- name: Use Node.js 18.9.0
uses: actions/setup-node@v1
with:
node-version: 18

- run: yarn ci
//before the first 'run' each "run" is a script from your project:
- run: yarn run eslint
- run: yarn run test --watchAll 
