name: Run Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Java Linter
      run: mvn checkstyle:check

    - name: Install modules
      working-directory: ./src/react
      run: yarn

    - name: Run Eslint
      working-directory: ./src/react
      run: yarn run eslint src --ext .js,.jsx,.ts,.tsx
