name: Run Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Java Linter
      run: mvn site

    - name: JAVA CodeCheck HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'target/site/checkstyle.html'

    - name: Install modules
      working-directory: ./src/react
      run: yarn
    - name: Run Eslint
      working-directory: ./src/react
      run: yarn run eslint src --ext .js,.jsx,.ts,.tsx
